/**
 * Shape: m66-explicit-routing-proof
 * =================================
 * A bounded proof shape that preserves explicit planner, executor, and verifier routes through genuine registered-tool dispatch and records isolated runtime role evidence.
 *
 * Generated by the shape-builder deterministic constructor.
 * ONE-LINE RULE: Shapes are siblings — they stand on the substrate,
 * never build on each other.
 */

import {
  SpawnGuard,
  spawnSubagent,
  throwIfAborted,
  truncateWithNotice,
  type SubagentResult,
} from "../substrate";
import { formatRouteLabel, resolveShapePhaseRoute } from "../routes";

import type {
  OrchestrationShape,
  OrchestrationShapeContext,
  OrchestrationShapeResult,
} from "../types";

const PHASES = [
  {
    "name": "plan-proof",
    "role": "planner",
    "agentName": "planner",
    "prompt": "Read the original task and produce a concise proof plan. Do not modify files and do not invoke orchestration.",
    "expectedOutput": "A bounded plan identifying the two executor evidence writes and independent verification criteria."
  },
  {
    "name": "execute-proof-a",
    "role": "executor",
    "agentName": "coder",
    "prompt": "Use a file-writing tool to create bespoke-proof-a.txt in the task workspace containing exactly: bespoke route proof A. Do not modify any other file.",
    "expectedOutput": "The created file path and exact content."
  },
  {
    "name": "execute-proof-b",
    "role": "executor",
    "agentName": "coder",
    "prompt": "Use a file-writing tool to create bespoke-proof-b.txt in the task workspace containing exactly: bespoke route proof B. Do not modify any other file.",
    "expectedOutput": "The created file path and exact content."
  },
  {
    "name": "verify-proof",
    "role": "verifier",
    "agentName": "reviewer",
    "prompt": "Independently assess the prior role outputs. Return PASS only if both executor phases report their required evidence writes and all phase outputs stayed within scope. Do not invoke orchestration.",
    "expectedOutput": "A direct PASS or FAIL verdict with citations to prior phase output."
  }
] as const;
const MAX_FINAL_CHARS = 20_000;

export const m66ExplicitRoutingProofShape: OrchestrationShape = {
  name: "m66-explicit-routing-proof",
  description: "A bounded proof shape that preserves explicit planner, executor, and verifier routes through genuine registered-tool dispatch and records isolated runtime role evidence.",
  run: runM66ExplicitRoutingProof,
};

async function runM66ExplicitRoutingProof(context: OrchestrationShapeContext): Promise<OrchestrationShapeResult> {
  const { params, signal, onUpdate, inheritedModel, agents } = context;
  const emit = (text: string) => onUpdate?.({ content: [{ type: "text", text }] });
  const requestedVerifierCount = Math.max(1, params.verifierCount);
  const requiredSpawns = PHASES.reduce(
    (total, phase) => total + (phase.role === "verifier" ? requestedVerifierCount : 1),
    0,
  );
  const spawnGuard = new SpawnGuard(Math.min(params.maxSubagents, Math.max(8, requiredSpawns)));

  // Deterministic canary branch — no subagent spawn, no file mutation
  if (params.task.trim().startsWith("SHAPE_CANARY:m66-explicit-routing-proof")) {
    return {
      markdown: "# m66-explicit-routing-proof Canary: PASS\n\nDeterministic generated-shape canary passed.",
      details: {
        status: "pass",
        paradigm: "m66-explicit-routing-proof",
        canary: true,
        targetName: "m66-explicit-routing-proof",
        spawnedCount: 0,
        spawnedCap: 0,
      },
    };
  }

  const outputs: SubagentResult[] = [];
  const outputRecords: Array<{ phase: string; role: string; instance: number; output: SubagentResult }> = [];

  for (const [index, phase] of PHASES.entries()) {
    throwIfAborted(signal);
    const instanceCount = phase.role === "verifier" ? requestedVerifierCount : 1;
    const route = resolveShapePhaseRoute(phase.role, phase.agentName, params);
    const priorOutputs = [...outputs];
    const launches = Array.from({ length: instanceCount }, (_, instanceIndex) => {
      const spawned = spawnGuard.reserve();
      emit(`m66-explicit-routing-proof: phase ${index + 1}/${PHASES.length} ${phase.name} spawning ${phase.agentName} instance ${instanceIndex + 1}/${instanceCount} on ${formatRouteLabel(route)} (${spawned}/${spawnGuard.cap}).`);
      return spawnSubagent(
        phase.agentName,
        buildPhasePrompt(phase, params.task, priorOutputs),
        { agents, cwd: params.cwd, allowLocalModel: params.allowLocalModel, signal, inheritedModel, onProgress: emit, modelOverride: route },
      );
    });
    // Explicit verifierCount is a parallel independent-verifier contract.
    const phaseOutputs = await Promise.all(launches);
    outputs.push(...phaseOutputs);
    phaseOutputs.forEach((output, instance) => outputRecords.push({ phase: phase.name, role: phase.role, instance: instance + 1, output }));
  }

  const status = outputs.every((output) => output.exitCode === 0) ? "pass" : "fail";
  const markdown = buildReport(status, params.task, spawnGuard, outputs);
  return {
    markdown,
    details: {
      status,
      paradigm: "m66-explicit-routing-proof",
      spawnedCount: spawnGuard.spawned,
      spawnedCap: spawnGuard.cap,
      terminationCondition: "Run each declared phase once, fan out the verifier phase according to verifierCount, aggregate child exit status, and stop.",
      evidenceModel: "Registered-tool lifecycle artifacts plus nonempty explicit routing requirements and isolated per-role runtime results.",
      failureBehavior: "Fail when any child exits nonzero, any required route is absent, or either evidence write is not reported.",
      controls: {
        executorConcurrency: params.concurrency,
        verifierCount: requestedVerifierCount,
        preflight: params.preflight,
        hardGates: params.hardGates,
        contextIsolation: "separate pi --no-session subprocess per spawn",
      },
      routingRequirements: [
        { role: "planner", agentName: params.plannerAgent, provider: params.plannerProvider, model: params.plannerModel, essential: Boolean(params.plannerProvider || params.plannerModel) },
        { role: "executor", agentName: params.executorAgent, provider: params.executorProvider, model: params.executorModel, essential: Boolean(params.executorProvider || params.executorModel) },
        { role: "verifier", agentName: params.verifierAgent, provider: params.verifierProvider, model: params.verifierModel, essential: Boolean(params.verifierProvider || params.verifierModel), count: requestedVerifierCount },
      ].filter((route) => route.essential),
      roleResults: outputRecords.map(({ phase, role, instance, output }) => ({
        phase, role, instance, agentName: output.agentName,
        provider: output.provider, model: output.model,
        isolatedContext: true, exitCode: output.exitCode,
      })),
      verifierResults: outputRecords.filter((record) => record.role === "verifier").map(({ phase, instance, output }) => ({
        phase, role: "verifier", instance, agentName: output.agentName,
        provider: output.provider, model: output.model,
        status: output.exitCode === 0 ? "pass" : "fail", isolatedContext: true,
      })),
      outputs: outputs.map((output) => ({
        agentName: output.agentName,
        provider: output.provider,
        model: output.model,
        exitCode: output.exitCode,
        durationMs: output.durationMs,
        text: truncateWithNotice(output.text, 2000, "phase output"),
      })),
    },
  };
}

function buildPhasePrompt(phase: typeof PHASES[number], originalTask: string, prior: SubagentResult[]): string {
  return [
    `You are running phase "${phase.name}" (role: ${phase.role}) in a bounded orchestration shape.`,
    "Do not invoke recursive orchestration. Work only on the phase prompt below.",
    `Original task:\n${originalTask}`,
    prior.length ? `Prior phase outputs:\n${prior.map((item, index) => `[${index + 1}] ${item.agentName}: ${truncateWithNotice(item.text, 3000, "prior output")}`).join("\n\n")}` : "Prior phase outputs: none.",
    `Phase prompt:\n${phase.prompt}`,
    `Expected output:\n${phase.expectedOutput}`,
  ].join("\n\n");
}

function buildReport(status: "pass" | "fail", task: string, spawnGuard: SpawnGuard, outputs: SubagentResult[]): string {
  const lines = [
    `# m66-explicit-routing-proof Orchestration: ${status.toUpperCase()}`,
    "",
    `**Task:** ${truncateWithNotice(task, 2000, "task")}`,
    `**Subagents spawned:** ${spawnGuard.spawned}/${spawnGuard.cap}`,
    `**Termination:** Run each declared phase once, fan out the verifier phase according to verifierCount, aggregate child exit status, and stop.`,
    `**Evidence model:** Registered-tool lifecycle artifacts plus nonempty explicit routing requirements and isolated per-role runtime results.`,
    "",
    "## Phase outputs",
  ];
  outputs.forEach((output, index) => {
    lines.push(`### Phase ${index + 1}: ${PHASES[index]?.name ?? output.agentName}`, truncateWithNotice(output.text, 3000, "phase output"));
  });
  lines.push("", "## Orchestration Used", "Build-time generated M6.6 proof shape for explicit route, context-isolation, executor-control, and two-verifier dispatch acceptance.");
  return truncateWithNotice(lines.join("\n"), MAX_FINAL_CHARS, "final report");
}
