/**
 * Shape: preregistered-concurrency-spike
 * ======================================
 * Reusable falsifier-first concurrency/real-time spike loop. Validates a concurrency or real-time spike strictly against an EXTERNALLY pre-registered, sha256-content-hash-frozen gate authored before any results exist. The shape refuses to PASS if the pre-registration artifact was tampered with after freeze, if the pass/fail thresholds were tuned post-hoc, or if measured raw evidence misses the pre-registered thresholds. Encodes pre-registration discipline as first-class phases rather than trusting any single agent narrative.
 *
 * Generated by the shape-builder deterministic constructor.
 * ONE-LINE RULE: Shapes are siblings — they stand on the substrate,
 * never build on each other.
 */

import {
  SpawnGuard,
  spawnSubagent,
  SubagentDetachedError,
  throwIfAborted,
  truncateWithNotice,
  type SubagentResult,
} from "../substrate";
import { RunStateStore, collectSurvivorResult } from "../run-state";
import { canonicalShapeRole, formatRouteLabel, resolveShapePhaseRoute } from "../routes";

import type {
  OrchestrationShape,
  OrchestrationShapeContext,
  OrchestrationShapeResult,
} from "../types";

const PHASES = [
  {
    "name": "implement",
    "role": "executor",
    "agentName": "coder",
    "prompt": "You implement a concurrency/real-time spike STRICTLY to the externally frozen pre-registration referenced in the task. The task contains: (a) the spike goal, (b) the path to the FROZEN pre-registration artifact, and (c) its frozen sha256 reference hash. Read the pre-registration artifact but DO NOT modify it in any way (it is content-hash locked). Build only what the pre-registration specifies. Produce real, compilable/runnable source and build files using write/edit/bash tools - a text-only description is a FAILURE. Do not implement anything that tunes, weakens, or reinterprets the pre-registered pass/fail thresholds. If the pre-registration is ambiguous, implement the most falsifiable interpretation and note the ambiguity; never relax a threshold to make passing easier.",
    "expectedOutput": "A list of created/modified source and build artifacts (paths) implementing the spike exactly to the frozen spec, plus an explicit statement that the pre-registration artifact was NOT modified."
  },
  {
    "name": "measure",
    "role": "executor",
    "agentName": "coder",
    "prompt": "You build and run the spike implemented in the prior phase and collect RAW evidence exactly as the frozen pre-registration's metrics demand (e.g. concurrency proof, xrun counts, thread-safety/UB/sanitizer output, latency). Use bash to compile and execute; capture real command output. Record raw numbers and tool output verbatim - do not summarize away failures, do not retry until green, do not alter thresholds. If the build or run fails, report the exact failure faithfully. Never edit the frozen pre-registration artifact. The gate must be computable from the raw evidence you collect.",
    "expectedOutput": "Raw measured evidence (verbatim command output, counts, sanitizer/UB results) sufficient to compute every pre-registered pass/fail metric, with the exact build and run commands used."
  },
  {
    "name": "verify",
    "role": "verifier",
    "agentName": "reviewer",
    "prompt": "You are an INDEPENDENT cross-lab verifier. Do not trust the executor narrative. Perform falsifier-first integrity checks: (1) HASH INTEGRITY - use bash to re-compute the sha256 of the FROZEN pre-registration artifact at the path given in the task and assert it EQUALS the frozen reference hash given in the task; if it differs, the pre-registration was tampered with after freeze - this is an automatic FAIL. (2) GATE FIDELITY - confirm every pass/fail threshold used was read from the frozen pre-registration and NOT changed; recompute the gate from the raw evidence collected in the measure phase. (3) NO TUNING - confirm nothing in the implementation or measurement weakened a threshold, special-cased the test, or selectively reported. (4) DETERMINISM/SOUNDNESS - sanity-check the evidence for UB, data races, or non-reproducibility. Emit a strict verdict.",
    "expectedOutput": "A strict verdict block: HASH_INTEGRITY pass/fail (with recomputed sha256 vs frozen reference), GATE_FIDELITY pass/fail, NO_TUNING pass/fail, plus per-metric measured-value-vs-threshold table and an overall VERIFY: PASS or VERIFY: FAIL with citations."
  },
  {
    "name": "verdict",
    "role": "aggregator",
    "agentName": "reviewer",
    "prompt": "You deterministically aggregate the prior phases into a final verdict. Emit FINAL: PASS only if ALL of the following hold: the verify phase reported HASH_INTEGRITY pass, GATE_FIDELITY pass, NO_TUNING pass, AND every pre-registered pass/fail threshold was met by the raw measured evidence. Otherwise emit FINAL: FAIL and quote the pre-declared fallback verbatim from the frozen pre-registration artifact (the fallback that was committed BEFORE any results existed). Do not invent a new fallback. Do not soften a FAIL into a PASS. State the single decisive reason for the verdict.",
    "expectedOutput": "FINAL: PASS or FINAL: FAIL, the decisive reason, and - on FAIL - the verbatim pre-declared fallback from the frozen pre-registration."
  }
] as const;
const MAX_FINAL_CHARS = 20_000;

export const preregisteredConcurrencySpikeShape: OrchestrationShape = {
  name: "preregistered-concurrency-spike",
  description: "Reusable falsifier-first concurrency/real-time spike loop. Validates a concurrency or real-time spike strictly against an EXTERNALLY pre-registered, sha256-content-hash-frozen gate authored before any results exist. The shape refuses to PASS if the pre-registration artifact was tampered with after freeze, if the pass/fail thresholds were tuned post-hoc, or if measured raw evidence misses the pre-registered thresholds. Encodes pre-registration discipline as first-class phases rather than trusting any single agent narrative.",
  run: runPreregisteredConcurrencySpike,
};

async function runPreregisteredConcurrencySpike(context: OrchestrationShapeContext): Promise<OrchestrationShapeResult> {
  const { params, signal, onUpdate, inheritedModel, agents } = context;
  const emit = (text: string) => onUpdate?.({ content: [{ type: "text", text }] });
  const requestedVerifierCount = Math.max(1, params.verifierCount);
  const requiredSpawns = PHASES.reduce(
    (total, phase) => total + (canonicalShapeRole(phase.role, phase.agentName, params) === "verifier" && phase.role === "verifier" ? requestedVerifierCount : 1),
    0,
  );
  const spawnGuard = new SpawnGuard(Math.min(params.maxSubagents, Math.max(4, requiredSpawns)));

  // Deterministic canary branch — no subagent spawn, no file mutation
  if (params.task.trim().startsWith("SHAPE_CANARY:preregistered-concurrency-spike")) {
    return {
      markdown: "# preregistered-concurrency-spike Canary: PASS\n\nDeterministic generated-shape canary passed.",
      details: {
        status: "pass",
        paradigm: "preregistered-concurrency-spike",
        canary: true,
        targetName: "preregistered-concurrency-spike",
        spawnedCount: 0,
        spawnedCap: 0,
      },
    };
  }

  const outputs: SubagentResult[] = [];
  const outputRecords: Array<{ phase: string; role: string; instance: number; output: SubagentResult }> = [];

  // Checkpoint/resume wiring (ABORT-RESUME-DESIGN.md): persist each completed
  // phase; spawn phases in abort-survivor mode so a tool-call abort detaches
  // the running child instead of killing it, and a later
  // a later resume invocation ({ resume: "<runId>" }) picks up where the run left off.
  const runId = context.runId;
  const resume = context.resumeState;
  const store = resume
    ? RunStateStore.open(resume.state.runId)
    : runId
      ? RunStateStore.create(runId, "preregistered-concurrency-spike", params.task,
          serializableParams(params), PHASES.map((phase) => phase.name))
      : undefined;

  for (const [index, phase] of PHASES.entries()) {
    const isVerifierPhase = phase.role === "verifier";
    const instanceCount = isVerifierPhase ? requestedVerifierCount : 1;

    // A multi-verifier checkpoint is persisted as an array; legacy single
    // checkpoints remain readable for backward-compatible resume.
    const checkpoint = resume?.checkpoints.get(index) as SubagentResult | SubagentResult[] | undefined;
    if (checkpoint) {
      emit(`preregistered-concurrency-spike: phase ${index + 1}/${PHASES.length} ${phase.name} restored from checkpoint (resume).`);
      const restored = Array.isArray(checkpoint) ? checkpoint : [checkpoint];
      outputs.push(...restored);
      restored.forEach((output, instance) => outputRecords.push({ phase: phase.name, role: phase.role, instance: instance + 1, output }));
      continue;
    }

    // Detached-survivor collection remains exact for single-instance phases.
    const survivor = instanceCount === 1 ? resume?.survivors.get(index) : undefined;
    if (survivor && store) {
      const collected = await collectSurvivorResult<SubagentResult>(survivor, emit, signal, "preregistered-concurrency-spike");
      if (collected) {
        store.checkpointPhase(index, phase.name, collected);
        outputs.push(collected);
        outputRecords.push({ phase: phase.name, role: phase.role, instance: 1, output: collected });
        continue;
      }
      emit(`preregistered-concurrency-spike: survivor for phase ${phase.name} yielded no result (pid dead, no result file) — respawning phase.`);
    }

    throwIfAborted(signal);
    const priorOutputs = [...outputs];
    const route = resolveShapePhaseRoute(phase.role, phase.agentName, params);
    const launches = Array.from({ length: instanceCount }, (_, instanceIndex) => {
      const spawned = spawnGuard.reserve();
      emit(`preregistered-concurrency-spike: phase ${index + 1}/${PHASES.length} ${phase.name} spawning ${phase.agentName} instance ${instanceIndex + 1}/${instanceCount} on ${formatRouteLabel(route)} (${spawned}/${spawnGuard.cap}).`);
      return spawnSubagent(
        phase.agentName,
        buildPhasePrompt(phase, params.task, priorOutputs),
        {
          agents,
          cwd: params.cwd,
          allowLocalModel: params.allowLocalModel,
          signal,
          inheritedModel,
          onProgress: emit,
          modelOverride: route,
          ...(store && instanceCount === 1
            ? {
                abortSurvival: {
                  resultFile: store.survivorResultPath(index, phase.name),
                  manifestFile: store.survivorManifestPath(index, phase.name),
                  phaseName: phase.name,
                  phaseIndex: index,
                },
              }
            : {}),
        },
      );
    });

    let phaseOutputs: SubagentResult[];
    try {
      // Promise.all is intentional: explicit verifierCount means independent
      // verifier contexts run in parallel before the aggregator phase.
      phaseOutputs = await Promise.all(launches);
    } catch (error) {
      if (error instanceof SubagentDetachedError && store) {
        store.markDetached(index, phase.name, error.manifest);
        throw new Error(
          `Orchestration aborted mid-phase but the ${phase.name} subagent (pid=${error.manifest.pid}) ` +
            `continues in the background. Resume this run by re-invoking the orchestrate tool with { resume: "${store.runId}" }. ` +
            `Completed phases are checkpointed and will not be re-executed.`,
        );
      }
      throw error;
    }
    store?.checkpointPhase(
      index,
      phase.name,
      instanceCount === 1 ? phaseOutputs[0] : (phaseOutputs as unknown as SubagentResult),
    );
    outputs.push(...phaseOutputs);
    phaseOutputs.forEach((output, instance) => outputRecords.push({ phase: phase.name, role: phase.role, instance: instance + 1, output }));
  }

  const status = outputs.every((output) => output.exitCode === 0) ? "pass" : "fail";
  const markdown = buildReport(status, params.task, spawnGuard, outputs, params);
  return {
    markdown,
    details: {
      status,
      paradigm: "preregistered-concurrency-spike",
      spawnedCount: spawnGuard.spawned,
      spawnedCap: spawnGuard.cap,
      terminationCondition: "Runs the four phases (implement, measure, verify, verdict) exactly once in order, then stops. No iteration and no loops.",
      evidenceModel: "Completion is proven by: (1) real build/run artifacts from implement and measure; (2) the verify phase's independently recomputed sha256 of the pre-registration equalling the frozen reference hash supplied in the task (proving the gate was untouched after freeze); (3) a PASS/FAIL verdict computed from raw evidence against the frozen thresholds.",
      failureBehavior: "The shape FAILS if the recomputed pre-registration sha256 does not match the frozen reference (tampering), if any pass/fail threshold was altered or could not be computed from raw evidence, or if the measured evidence misses a pre-registered threshold. On FAIL the verdict phase emits the verbatim pre-declared fallback from the frozen pre-registration.",
      controls: {
        executorConcurrency: params.concurrency,
        verifierCount: requestedVerifierCount,
        preflight: params.preflight,
        hardGates: params.hardGates,
        contextIsolation: "separate pi --no-session subprocess per spawn",
      },
      routingRequirements: [
        { role: "planner", agentName: params.plannerAgent, provider: params.plannerProvider, model: params.plannerModel, essential: Boolean(params.plannerProvider || params.plannerModel) },
        { role: "executor", agentName: params.executorAgent, provider: params.executorProvider, model: params.executorModel, essential: Boolean(params.executorProvider || params.executorModel) },
        { role: "verifier", agentName: params.verifierAgent, provider: params.verifierProvider, model: params.verifierModel, essential: Boolean(params.verifierProvider || params.verifierModel), count: requestedVerifierCount },
      ].filter((route) => route.essential),
      roleResults: outputRecords.map(({ phase, role, instance, output }) => ({
        phase, role, instance, agentName: output.agentName,
        provider: output.provider, model: output.model,
        isolatedContext: true, exitCode: output.exitCode,
      })),
      verifierResults: outputRecords.filter((record) => record.role === "verifier").map(({ phase, instance, output }) => ({
        phase, role: "verifier", instance, agentName: output.agentName,
        provider: output.provider, model: output.model,
        status: output.exitCode === 0 ? "pass" : "fail", isolatedContext: true,
      })),
      outputs: outputs.map((output) => ({
        agentName: output.agentName,
        provider: output.provider,
        model: output.model,
        exitCode: output.exitCode,
        durationMs: output.durationMs,
        text: truncateWithNotice(output.text, 2000, "phase output"),
      })),
    },
  };
}

/** Serializable subset of params persisted for resume re-dispatch. */
function serializableParams(params: OrchestrationShapeContext["params"]): Record<string, unknown> {
  return JSON.parse(JSON.stringify(params)) as Record<string, unknown>;
}

function buildPhasePrompt(phase: typeof PHASES[number], originalTask: string, prior: SubagentResult[]): string {
  return [
    `You are running phase "${phase.name}" (role: ${phase.role}) in a bounded orchestration shape.`,
    "Do not invoke recursive orchestration. Work only on the phase prompt below.",
    `Original task:\n${originalTask}`,
    prior.length ? `Prior phase outputs:\n${prior.map((item, index) => `[${index + 1}] ${item.agentName}: ${truncateWithNotice(item.text, 3000, "prior output")}`).join("\n\n")}` : "Prior phase outputs: none.",
    `Phase prompt:\n${phase.prompt}`,
    `Expected output:\n${phase.expectedOutput}`,
  ].join("\n\n");
}

function buildReport(
  status: "pass" | "fail",
  task: string,
  spawnGuard: SpawnGuard,
  outputs: SubagentResult[],
  params: OrchestrationShapeContext["params"],
): string {
  const lines = [
    `# preregistered-concurrency-spike Orchestration: ${status.toUpperCase()}`,
    "",
    `**Task:** ${truncateWithNotice(task, 2000, "task")}`,
    `**Subagents spawned:** ${spawnGuard.spawned}/${spawnGuard.cap}`,
    `**Routes:** Executor=${formatRouteLabel(resolveShapePhaseRoute("executor", params.executorAgent, params))}; Verifier=${formatRouteLabel(resolveShapePhaseRoute("verifier", params.verifierAgent, params))}.`,
    `**Termination:** Runs the four phases (implement, measure, verify, verdict) exactly once in order, then stops. No iteration and no loops.`,
    `**Evidence model:** Completion is proven by: (1) real build/run artifacts from implement and measure; (2) the verify phase's independently recomputed sha256 of the pre-registration equalling the frozen reference hash supplied in the task (proving the gate was untouched after freeze); (3) a PASS/FAIL verdict computed from raw evidence against the frozen thresholds.`,
    "",
    "## Phase outputs",
  ];
  outputs.forEach((output, index) => {
    lines.push(`### Phase ${index + 1}: ${PHASES[index]?.name ?? output.agentName}`, truncateWithNotice(output.text, 3000, "phase output"));
  });
  lines.push("", "## Orchestration Used", "preregistered-concurrency-spike runs a falsifier-first concurrency/real-time spike against an EXTERNALLY frozen pre-registration. USAGE CONTRACT: before invoking this shape, the orchestrator must (1) author a pre-registration artifact containing metrics, pass/fail thresholds, and a pre-declared fallback, and (2) deterministically freeze it with sha256 (non-LLM). The frozen artifact path and reference hash are then passed inside the task. The shape implements strictly to the frozen spec, measures raw evidence, independently re-verifies hash integrity (refusing to PASS if the pre-registration was touched or the gate tuned), and emits PASS or the pre-declared fallback. The deterministic freeze stays orchestrator-held because the generated-shape phase model spawns an LLM subagent per phase and has no non-LLM phase primitive; the shape encodes the post-freeze discipline and enforces non-tampering as a first-class verify phase.");
  return truncateWithNotice(lines.join("\n"), MAX_FINAL_CHARS, "final report");
}
