/**
 * Shape: venue-rescue-synthesis
 * =============================
 * A reusable research-to-deliverable pipeline that turns a struggling venue or business unit into an investor-grade rescue plan: cheap text research and a vision-based brand/aesthetic audit feed a specialist financial-narrative phase, a strong synthesis-and-critique phase fuses everything into a strategy with wild and practical options, a design phase builds a stylish interactive HTML/JS deliverable, and an independent verifier checks it. Phases route to distinct models by agent name.
 *
 * Generated by the shape-builder deterministic constructor.
 * ONE-LINE RULE: Shapes are siblings — they stand on the substrate,
 * never build on each other.
 */

import {
  SpawnGuard,
  spawnSubagent,
  throwIfAborted,
  truncateWithNotice,
  type SubagentResult,
} from "../substrate";

import type {
  OrchestrationShape,
  OrchestrationShapeContext,
  OrchestrationShapeResult,
  NormalizedParams,
} from "../types";
import { resolveRouteOverride, formatRouteLabel } from "../routes";

/**
 * Resolve the per-role model override for a phase, honoring the executor/
 * verifier/planner override params via the shared helper. Phases whose role is
 * not one of these (researcher/analyst/synthesist/builder) route by agent name
 * as before (undefined override → inherit the agent's configured model).
 */
function phaseRouteOverride(
  role: string,
  params: NormalizedParams,
): { model?: string; provider?: string } | undefined {
  if (role === "verifier") return resolveRouteOverride(params.verifierModel, params.verifierProvider);
  if (role === "executor") return resolveRouteOverride(params.executorModel, params.executorProvider);
  if (role === "planner") return resolveRouteOverride(params.plannerModel, params.plannerProvider);
  return undefined;
}

const PHASES = [
  {
    "name": "text-research",
    "role": "researcher",
    "agentName": "bham-market-researcher",
    "prompt": "Research the local market, competitors, demand signals, and brand exposure relevant to the task. Use web search and browsing; cite URLs; separate verified facts from inference. Write a concise structured research brief and save it to the run directory.",
    "expectedOutput": "A research brief: market overview, competitor table, demand/seasonality signals, brand exposure findings, gaps, with citations."
  },
  {
    "name": "visual-brand-audit",
    "role": "researcher",
    "agentName": "bham-brand-vision",
    "prompt": "Using vision and browser tools, audit the brand web presence and visual identity: capture and read screenshots, assess typography, colour, imagery, tone, UX clarity, and mobile usability against a stylish-minimal modern standard. Save a visual-brand audit to the run directory.",
    "expectedOutput": "A screenshot-grounded visual-brand audit with strengths, weaknesses, and aesthetic direction."
  },
  {
    "name": "financial-narrative",
    "role": "analyst",
    "agentName": "bham-financial-analyst",
    "prompt": "Read the provided management accounts and entity accounts including the after-head-office-cuts apportionment view. Produce an evidence-based P&L narrative: revenue mix, gross margin, direct costs, overheads, head-office apportionment, EBITDA net result, period trends, the effect of cutting head-office costs, and a clear breakeven sales level. Tie every claim to source figures; distinguish actuals from projections. Save the narrative to the run directory.",
    "expectedOutput": "A financial P&L narrative with breakeven and an explicit after-HO-cuts scenario, every figure traceable to sources."
  },
  {
    "name": "synthesis-critique",
    "role": "synthesist",
    "agentName": "bham-synthesis",
    "prompt": "You receive the prior research brief, visual-brand audit, the financial narrative, and any existing P&L narrative supplied in the task. Critique each input for weaknesses, bias, and gaps. Then synthesize a coherent rescue strategy integrating brand identity, market position, competitors, and financials. Provide BOTH bold wild ideas AND practical near-term moves, each with benefits, risks, and time-to-impact, plus realistic timeframes to profitability. Treat head-office and management cost reduction as one viable lever but not the only path; aim to restore the venue to a strong position rather than bare survival. Save a structured rescue plan to the run directory.",
    "expectedOutput": "A structured, investor-grade rescue plan: critique of inputs, integrated strategy, wild and practical options with benefits/risks/timeframes, and a timeline to profitability."
  },
  {
    "name": "interactive-build",
    "role": "builder",
    "agentName": "bham-web-designer",
    "prompt": "Build a self-contained, investor-facing interactive HTML/JS application presenting the synthesized rescue plan. Requirements: clear strong narrative; simple to read; business-like but stylish minimal aesthetic with excellent typography; interactive graphs for financials, timeframes-to-profitability, and scenario comparisons; responsive; ready to drop onto the brand website. Use real figures from the financial narrative and chart data. Avoid generic AI aesthetics. Save the site files to the run directory and report the path.",
    "expectedOutput": "A real, self-contained interactive HTML/JS site file with interactive graphs reflecting the rescue plan."
  },
  {
    "name": "verification",
    "role": "verifier",
    "agentName": "bham-verifier",
    "prompt": "Independently verify the deliverables with direct evidence: financial claims trace to source figures; the synthesis integrates brand, market, competitors, and financials; both wild and practical ideas appear with benefits/risks/timeframes; the head-office-cuts lever is present but not the sole path; the interactive site exists as a real file, renders, contains interactive graphs, and matches the stylish-minimal brief. Return a clear PASS or FAIL with cited evidence and any gaps.",
    "expectedOutput": "A PASS/FAIL verdict with cited evidence and a gap list."
  }
] as const;
const MAX_FINAL_CHARS = 20_000;

export const venueRescueSynthesisShape: OrchestrationShape = {
  name: "venue-rescue-synthesis",
  description: "A reusable research-to-deliverable pipeline that turns a struggling venue or business unit into an investor-grade rescue plan: cheap text research and a vision-based brand/aesthetic audit feed a specialist financial-narrative phase, a strong synthesis-and-critique phase fuses everything into a strategy with wild and practical options, a design phase builds a stylish interactive HTML/JS deliverable, and an independent verifier checks it. Phases route to distinct models by agent name.",
  run: runVenueRescueSynthesis,
};

async function runVenueRescueSynthesis(context: OrchestrationShapeContext): Promise<OrchestrationShapeResult> {
  const { params, signal, onUpdate, inheritedModel, agents } = context;
  const emit = (text: string) => onUpdate?.({ content: [{ type: "text", text }] });
  const spawnGuard = new SpawnGuard(Math.min(params.maxSubagents, 6));

  // Deterministic canary branch — no subagent spawn, no file mutation
  if (params.task.trim().startsWith("SHAPE_CANARY:venue-rescue-synthesis")) {
    return {
      markdown: "# venue-rescue-synthesis Canary: PASS\n\nDeterministic generated-shape canary passed.",
      details: {
        status: "pass",
        paradigm: "venue-rescue-synthesis",
        canary: true,
        targetName: "venue-rescue-synthesis",
        spawnedCount: 0,
        spawnedCap: 0,
      },
    };
  }

  const outputs: SubagentResult[] = [];

  for (const [index, phase] of PHASES.entries()) {
    throwIfAborted(signal);
    const spawned = spawnGuard.reserve();
    emit(`venue-rescue-synthesis: phase ${index + 1}/${PHASES.length} ${phase.name} spawning ${phase.agentName} (${spawned}/${spawnGuard.cap}).`);
    const modelOverride = phaseRouteOverride(phase.role, params);
    const result = await spawnSubagent(
      phase.agentName,
      buildPhasePrompt(phase, params.task, outputs),
      { agents, cwd: params.cwd, allowLocalModel: params.allowLocalModel, signal, inheritedModel, onProgress: emit, modelOverride },
    );
    outputs.push(result);
  }

  const status = outputs.every((output) => output.exitCode === 0) ? "pass" : "fail";
  const markdown = buildReport(status, params.task, spawnGuard, outputs, params);
  return {
    markdown,
    details: {
      status,
      paradigm: "venue-rescue-synthesis",
      spawnedCount: spawnGuard.spawned,
      spawnedCap: spawnGuard.cap,
      terminationCondition: "All six phases complete in sequence and the verifier returns a verdict; the run then stops.",
      evidenceModel: "Completion is proven by the research brief, visual-brand audit, financial narrative, synthesis rescue plan, a real interactive site file, and an independent verifier verdict, all present in the run directory.",
      failureBehavior: "Fail if any phase produces no artifact, if financial figures are untraceable, if only the cost-cutting path is offered, or if the interactive site is missing, static, or lacks interactive graphs.",
      outputs: outputs.map((output) => ({
        agentName: output.agentName,
        exitCode: output.exitCode,
        durationMs: output.durationMs,
        text: truncateWithNotice(output.text, 2000, "phase output"),
      })),
    },
  };
}

function buildPhasePrompt(phase: typeof PHASES[number], originalTask: string, prior: SubagentResult[]): string {
  return [
    `You are running phase "${phase.name}" (role: ${phase.role}) in a bounded orchestration shape.`,
    "Do not invoke recursive orchestration. Work only on the phase prompt below.",
    `Original task:\n${originalTask}`,
    prior.length ? `Prior phase outputs:\n${prior.map((item, index) => `[${index + 1}] ${item.agentName}: ${truncateWithNotice(item.text, 3000, "prior output")}`).join("\n\n")}` : "Prior phase outputs: none.",
    `Phase prompt:\n${phase.prompt}`,
    `Expected output:\n${phase.expectedOutput}`,
  ].join("\n\n");
}

function buildReport(status: "pass" | "fail", task: string, spawnGuard: SpawnGuard, outputs: SubagentResult[], params: NormalizedParams): string {
  const lines = [
    `# venue-rescue-synthesis Orchestration: ${status.toUpperCase()}`,
    "",
    `**Task:** ${truncateWithNotice(task, 2000, "task")}`,
    // Routes line derives from the SAME resolved verifier override passed to the
    // verification (role: verifier) spawn; specialist phases route by agent name.
    `**Routes:** Verifier=${formatRouteLabel(resolveRouteOverride(params.verifierModel, params.verifierProvider))} (other phases route by agent name)`,
    `**Subagents spawned:** ${spawnGuard.spawned}/${spawnGuard.cap}`,
    `**Termination:** All six phases complete in sequence and the verifier returns a verdict; the run then stops.`,
    `**Evidence model:** Completion is proven by the research brief, visual-brand audit, financial narrative, synthesis rescue plan, a real interactive site file, and an independent verifier verdict, all present in the run directory.`,
    "",
    "## Phase outputs",
  ];
  outputs.forEach((output, index) => {
    lines.push(`### Phase ${index + 1}: ${PHASES[index]?.name ?? output.agentName}`, truncateWithNotice(output.text, 3000, "phase output"));
  });
  lines.push("", "## Orchestration Used", "venue-rescue-synthesis runs cheap text research and a vision-based brand audit, then a specialist financial narrative, then a strong synthesis-and-critique that fuses everything into a rescue strategy with wild and practical options, then a design phase that builds a stylish interactive investor site, then an independent verification.");
  return truncateWithNotice(lines.join("\n"), MAX_FINAL_CHARS, "final report");
}
